### ISSUE TITLE
Missing phone number to apply

### ISSUE THREAD

**Issue by ak9250** [udaybhaskar578/LinkedIn-Easy-Apply-Automation#3]
error at the field for phone number and presently their is no field for phone number within the code for linkedineasyapply.py file

**Comment by udaybhaskar578** [comment]
<img width="629" alt="screen shot 2017-07-21 at 11 00 18 am" src="https://user-images.githubusercontent.com/5334224/28476197-f3d950aa-6e03-11e7-8989-51b345d99acd.png">


There is a phone number field during the easy apply process.
That phone number is related to your profile, that has nothing do with the code.

**Comment by ak9250** [comment]
ok yeah I got that working
